spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_project?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 12345678
  #redis
  redis:
    host: 127.0.0.01
    port: 6379  #可不配，因为底层默认值为6379

server:
  port: 8080

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.kira.order.mapper: DEBUG
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"